services:
  timescaledb:
    image: timescale/timescaledb:2.23.1-pg16
    restart: unless-stopped
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    volumes:
      - realtime_simulator_data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - timescaledb
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "8080:8080" 

  rlt-app:
    build: .
    restart: unless-stopped
    depends_on:
      - timescaledb
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: timescaledb
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE

volumes:
  realtime_simulator_data:
